spring.application.name=sahyadri_multitradelinks

server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/sahyadri_multitradelinks?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Auto-create schema
spring.jpa.properties.hibernate.hbm2ddl.auto=update


